### PR TITLE
fix: skip sorting non package.json files

### LINKED ISSUE #4: False-positive invocation for package-lock.json and composer.json
Hi again @matzkoh! I just tried 2.0.0 and it worked perfectly! 🎉 ✨

Once thing I noticed by looking into the [changes](https://github.com/matzkoh/prettier-plugin-packagejson/commit/241059d558707bbff4a11ed4f446458f31c67ea6) you've made is that now the plugin mistakenly grabs `package-lock.json` and `composer.json`, not only `package.json`.

Here is the reason: https://github.com/prettier/prettier/blob/91c20f7fbe22f68480820fcf322e7e099b22d82e/src/language-js/index.js#L45-L55

Also because of https://github.com/prettier/prettier/issues/6059, there is a small chance that `json-strignify` parser will be used in other cases too.

If a repo contains any of the files and a team either has a [pre-commit hook](https://prettier.io/docs/en/precommit.html) or runs [`prettier --check`](https://prettier.io/docs/en/cli.html#check) in CI, things won't work as expected.

We are using `yarn` in our projects, so the issue does not affect us directly. However, I guess someone will get confused sooner or later if the popularity of your plugin grows. You can probably solve the problem by creating a new language (`packagejson` or `package-json`) and a separate parser for it, which will invoke `sort-package-json` as well as bits of `json-stringify`. The new language will hopefully take precedence, but I'm quite not sure (https://github.com/prettier/prettier/issues/5919 / https://github.com/prettier/prettier/pull/6113).

It's quite easy to test the right behaviour by creating a couple of extra test cases with virtual files called `package-lock.json`, `compose.json` and `foobar.json`. Fields should not be sorted there. WDYT?

### PR DESCRIPTION
**Pull request by remcohaszing**
Closes #4

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -1,3 +1,4 @@
+const path = require('path')
```
Comment (kachkaev) [inline lib/index.js]: Introducing `path` as a dependency will make this plugin Node.js only. I'm not planning to use the package in the browser myself, but it's a bit of a shame that others won't be able to just because of this one line.

How about doing something like `/(\\\/)package\.json$/i.test(options.filepath)` to check if we're dealing with `package.json`?

Also adding test for `compose.json`, `package-lock.json` and some `foo-bar.json` will be useful.

Comment (remcohaszing) [reply lib/index.js]: I’m not fond of the way tests are setup. This is not extensible. Can I introduce jest?

Comment (kachkaev) [reply lib/index.js]: Introducing Jest would probably make the scope of this PR too wide. IMHO something like this would be enough for now:


```js
// test/index.js

const prettier = require("prettier")

const input = `...`

const expected = `...`

;["package.json", "Package.json", "package.JSON"].forEach((filepath) => {
  const output = prettier.format(input, {
    filepath,
    plugins: ["."],
  })
  console.assert(output === expected)
})

;["package-lock.json", "compose.json", "foo-bar.json", null].forEach(
  (element) => {
    const output = prettier.format(input, {
      filepath,
      plugins: ["."],
    })
    console.assert(output === input)
  },
)

console.log("\033[32mpassed!\033[39m")
```


P.S.:  [Having no semicolons is painful](https://medium.com/@WebReflection/an-open-letter-to-javascript-leaders-regarding-no-semicolons-82cec422d67d) 😔

Comment (remcohaszing) [reply lib/index.js]: I added tests as you requested, but with some changes:

- `package.json` is case sensitive. This may not be the case for case insensitive file systems, but `npm` simply doesn’t recognize a file named `Package.json` on my file system.
- Unrecognized JSON files aren’t parsed by prettier using the `json-stringify` parser, also they are formatted differently. I didn’t add tests for those.
- I added some test logging.
- I made the test script actually fail if an assertion failed.

File: test/index.js [hunk 2]
```diff
@@ -80,10 +80,35 @@ const expected = `{
...
+    plugins: ['.'],
+  })
+  console.log('Testing', filepath)
+  console.assert(output === expected, 'Output does not match expected output')
+  if (output !== expected) {
+    process.exitCode = 1
+  }
+  console.log()
 })
+;['Package.json', 'package.JSON', 'package-lock.json', 'composer.json', 'package.json/composer.json'].forEach(
```
Comment (kachkaev) [inline test/index.js]: Could you please add `undefined` or `null` to the list as well? Because we are manipulating `options.filepath` as a string, we should make sure Prettier does not throw an exception if this value is not provided (guess this can happen when the plugin is used on the front end). This would be a protection against someone removing `options.filepath && ` from the `if` you've added in `index.js`.

File: test/index.js [hunk 3]
```diff
@@ -80,10 +80,35 @@ const expected = `{
...
+  filepath => {
+    const output = prettier.format(input, {
+      filepath,
+      plugins: ['.'],
+    })
+    console.log('Testing', filepath)
+    console.assert(output === input, 'Output does not match input')
```
Comment (kachkaev) [inline test/index.js]: I guess we can still test `foobar.json` and any other arbitrary file names if instead of `output === input` we check for `output !== expected`. WDYT?

Comment (remcohaszing) [reply test/index.js]: This plugin patches the `json-stringify` parser. As seen [here](https://github.com/prettier/prettier/blob/master/src/language-js/index.js#L45-L55), this parser is only used for a very small number of hardcoded files.

Other JSON files are parsed using the `json` parser. Adding a test for these means it would test prettier internals, not this plugin. This would be similar to adding a test for a file named `.prettierrc`, `.eslintrc`, or even `foo.js`.

Comment (kachkaev) [reply test/index.js]: I agree with what you're saying, yet still think that it's useful to ensure the functionality of the plugin does not 'spill over' (even if looks unrealistic with the current implementation). What if something changes in Prettier itself, e.g. they decide to use `json-strigify` for all JSONs?

File: test/index.js (hunk 2 above)
Comment (remcohaszing) [reply test/index.js]: If `null` is passed, prettier simply crashes. I did add a test for `undefined`.

File: test/index.js (hunk 3 above)
Comment (remcohaszing) [reply test/index.js]: A more realistic scenario is if someone runs prettier from node and explicitly passes the `parser` option. I did this in the test case now, allowing to test any filepath option.

**Comment by matzkoh** [comment]
Thanks! 💯
